---
- name: Pre-tasks for Fedora
  hosts: test-Fedora-29
  become: yes
  user: fedora
  gather_facts: no

  pre_tasks:

    - name: Install python 2
      raw: dnf install -y python libselinux-python python2-dnf
      when: "'29' in version.stdout"

    #- name: Install python 3
    #  raw: dnf install -y python libselinux-python python3-dnf
    #  when: "'30' in version.stdout"
      
- name: Setup Fedora
  hosts: test-Fedora-29
  become: yes
  user: fedora
  gather_facts: yes  
  
  roles:
    - ../roles/update
    - ../roles/gnome
    - ../roles/chrome

- name: RHEL - Tooling.next
  hosts: test-Fedora-29
  user: fedora
  become: no
  gather_facts: yes

  roles:
    - ../roles/toolingnext-nvm