---
- name: Check free vm's space on OpenStack
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  
    - name: Gather information about previously created networks
      os_server_facts:
        filters:
          status: ACTIVE
      register: result

    - fail:
        msg: "Check openstack manualy"
      when: result.ansible_facts != "openstack_servers{{:}} []"