---
- name: Pre-tasks for Fedora
  hosts: all
  become: yes
  user: fedora
  gather_facts: yes

  pre_tasks:

    - name: Install python2-dnf
      raw: dnf install -y python libselinux-python python2-dnf
      when: ansible_distribution_version == "29"

    - name: Install python3-dnf
      raw: dnf install -y python libselinux-python python3-dnf
      when: ansible_distribution_version == "30"
      
- name: Setup Fedora
  hosts: all
  become: yes
  user: fedora
  gather_facts: yes  
  
  roles:
    - ../roles/update
    - ../roles/gnome
    - ../roles/chrome

- name: RHEL - Tooling.next
  hosts: all
  user: fedora
  become: no
  gather_facts: yes

  roles:
    - ../roles/toolingnext-nvm