---
- name: VERIFY - openstack
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  
    - name: Gather information about previously created networks
      os_networks_facts:
        auth:
          auth_url: "{{ auth_url }}"
          password: "{{ password }}"
          project_domain_id: "{{ project_domain_id }}"
          project_name: "{{ project_name }}"
          user_domain_name: "{{ user_domain_name }}"
          username: "{{ username }}"
      register: result