# Prepared to be used in Ansible Tower
---
- name: Check free vm's space on OpenStack
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Gather information about previously created networks
      os_server_facts:
      register: result

    - debug:
        msg: "{{result}}"

    - fail:
        msg: "Check openstack manualy"
      when: "'active' in result"
