---
- name: Check free vm's space on OpenStack
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  
    - name: Gather information about previously created networks
      os_server_facts:
        auth:
            username: 
            password: 
            project_name: 
            project_domain_id: 
            user_domain_name: 
            auth_url: 
     #   filters:
     #     vm_state: active
      register: result

    - fail:
        msg: "Check openstack manualy"
      when: result.ansible_facts != "openstack_servers{{:}} []"