---
- name: VERIFY - openstack
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  
    - name: Gather information about previously created networks
      os_networks_facts:
      register: result