---
- name: "Include variables for {{ ansible_distribution }}_{{ ansible_distribution_major_version }}"
  include_vars: "{{ ansible_distribution}}_{{ ansible_distribution_major_version }}.yml"

- name: "Update all packages (only on Ubuntu)"
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: "Install GNOME"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ gnome_pkgs }}"

- name: Create folder .config
  file:
    path: "/home/{{ ansible_ssh_user }}/.config"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"  

- name: Copy gnome-initial-setup-done
  copy:
    src: gnome-initial-setup-done
    dest: "/home/{{ ansible_ssh_user }}/.config/gnome-initial-setup-done"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0664

- name: Copy gnome-software-service.desktop
  copy:
    src: gnome-software-service.desktop
    dest: /etc/xdg/autostart/gnome-software-service.desktop
    owner: root
    group: root
    mode: 0644

- name: Copy gpk-update-icon.desktop
  copy:
    src: gpk-update-icon.desktop
    dest: /etc/xdg/autostart/gpk-update-icon.desktop
    owner: root
    group: root
    mode: 0644
